name: Build Toolbox Container

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build for Branches
        if: github.ref != 'refs/heads/main'
        run: |
          podman build -t "ghcr.io/${{ github.repository }}:${{ github.ref_name }}" .
          podman push "ghcr.io/${{ github.repository }}:${{ github.ref_name }}"

      - name: Build for main
        if: github.ref == 'refs/heads/main'
        run: |
          podman build -t "ghcr.io/${{ github.repository }}" .
          podman push "ghcr.io/${{ github.repository }}"
