name: Build Toolbox

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: run script
        run: ./run.sh
